version: 2

models:
  
  - name: sensor_speed
    description: This model shows the avgerage speed for each sensor
    columns:
      - name: sensorID
        description: The id of sensors and we have a total of 10 
        tests:
          - not_null
          - accepted_values:
              values: ['v10_0', 'v10_1', 'v10_2', 'v10_3', 'v10_4','v10_5', 'v10_6', 'v10_7', 'v10_8', 'v10_9']
      - name: gpsspeed
        description: The gps speed of the car
        
        